<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="ChetnaM-PC" ignored="0" name="suite21" tests="2" failures="1" timestamp="17 Mar 2017 11:47:47 GMT" time="398.279" errors="0">
  <testcase name="verify" time="197.534" classname="com.adv.qa.selenium.tests.currency.A036_BTZ_Elements_For_ICA_StructureTest"/>
  <testcase name="verify" time="168.781" classname="com.adv.qa.selenium.tests.currency.A037_ICA_Default_Trading_RelationshipsTest">
    <failure type="java.lang.AssertionError" message="New relationship between BTZ element for ICA structure ******************** not created expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: New relationship between BTZ element for ICA structure ******************** not created expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:513)
	at org.testng.Assert.assertTrue(Assert.java:42)
	at com.adv.qa.selenium.framework.Assert.assertTrue(Assert.java:43)
	at com.adv.qa.selenium.tests.currency.A037_ICA_Default_Trading_RelationshipsTest.verify(A037_ICA_Default_Trading_RelationshipsTest.java:73)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.InvokeMethodRunnable.runOne(InvokeMethodRunnable.java:54)
	at org.testng.internal.InvokeMethodRunnable.run(InvokeMethodRunnable.java:44)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- verify -->
</testsuite> <!-- suite21 -->
